//! Test vector generated by zkmsg-core (tools/zkmsg/core: args::build_circuit_args over a
//! two-leaf MerkleTree) from fixed test scalars — no real keys. The same vector was proven
//! on an iPhone and accepted on Sepolia alpha; `PHONE_MESSAGE_HASH` is the message hash from
//! that proof's facts.

pub const ROOT: felt252 = 0x4839405b29c8a2d146b62cc00a67ac54549a2dbe6d4b5e160f6a0c2a7fd4aca;
pub const SENDER_SCAN_PRIV: felt252 = 0x5e11de5c0ffee;
pub const RECIPIENT_SCAN_PUB: felt252 = 0x2faa66d3d78685cbd92013f0c0b44f6cd6c199c3984ad9eba913d1dbd6f0a9c;
pub const EPHEMERAL_PRIV: felt252 = 0xe9e3e7a1c0df;
pub const SENDER_LEAF_INDEX: u32 = 0;
pub const RECIPIENT_LEAF_INDEX: u32 = 1;
pub const COMMITMENT: felt252 = 0x3841cbcc32e9328400d8ad94f1600c4144c4effd462626b00513d2ec836b62c;
pub const EPHEMERAL_PUBKEY: felt252 = 0x275597a0fd9372d62124e23ff1a82ff06d608b7e201f2e4b70e474730ac8c81;

// The spike deployment the phone proof was made against, and its content hash.
pub const PHONE_PROVER: felt252 = 0x06d46be2b5b11dcdf62e395ab7aec099e4f7bb902c796f5d134b761275497ba3;
pub const PHONE_STORE: felt252 = 0x012f44de607f0108e460ebfc9eb23d8d2328d3bbc3f8d2a4d3698593c9accc4a;
pub const PHONE_CONTENT_HASH: felt252 = 0xc0ffee;
pub const PHONE_MESSAGE_HASH: felt252 = 0x7ed8f8d37995709d00420d34515c3b74f300f0618337d23c96293294a4fd9e5;

pub fn sender_path() -> Array<felt252> {
    array![
        0x2faa66d3d78685cbd92013f0c0b44f6cd6c199c3984ad9eba913d1dbd6f0a9c,
        0x1fb7169b936dd880cb7ebc50e932a495a60e0084cdab94a681040cb4006e1a0,
        0x17b96a8cee53f9566e4a318ccfe4bd54669d13d4e0ad518ce2905ac58ab6fcd,
        0x4268c203f18d361afc33a2d15356a4e64f2ca1f507bcefaf6e0daa5a2c4c4b8,
        0x31f82f7b110cf0fedec4381eb2b4ef7bbfb6241276ad81e99f23e64ea3457d2,
        0x55ce2b27b18dc167740cea55bfba4c920bf41455caf86c7ea4b9f7a614b3ac,
        0x1d2fd418edbc17be7e37a4d07fb3f910801b4a469fdcb6ba2ee6156294668,
        0x4f9b1a51a3ec0964b97c108efe065f54e6edd63cf2ef40dfc93f590437cae58,
        0x11d6400cced0057f253dd0f4906d202daec97295c251c1eb3a3ae13bf4442c5,
        0x2828ea3570ae2642abdf689ca78220d7dc45b7be0cc1ae97089a8fe89c739e1,
        0x54355cfccf17e98bf076e119955b58d531ab864c4f8b9606779ec0117ef3fac,
        0x3e170baf04d290e76759a1e2b67fa63739578d9883b7bdc6ba98afffc8992c5,
        0xce682ba73ca032d5dd0f2ccb29a1834b51d4dc850486cf08fdce6969203917,
        0x36480f71ded7948935f02b3755f9c79c3419476c69dfbe5ff9dc742b7136623,
        0x27a7269fa0c704fb77ff85b9579c7b81591a63ac1a68f5763e972d2941b10d1,
        0x1efdc54c79b7b0830cf54eaf000851aea6c543f7d12a193d4e2d596e905a7d8,
        0x3378095e3b6b35069a13555a585e41a8497cacf482520ed422d8a6addf0115a,
        0x1b31d8bdb4b4ca31bbf3902884c8be863315e8433a22e4aa2090c55f236b9a1,
        0x20a0570911d8a00c74573184ac517730de6f8cc0ca547f3449865eeb62b5b45,
        0x57ae865f1792ab222addcd9174fa8ef11d8d4e70149324ec901f7674a18d575,
    ]
}

pub fn recipient_path() -> Array<felt252> {
    array![
        0x5ebda1bbcc9508c02544b12d21a88e29146d531f444725e9bc560847456139,
        0x1fb7169b936dd880cb7ebc50e932a495a60e0084cdab94a681040cb4006e1a0,
        0x17b96a8cee53f9566e4a318ccfe4bd54669d13d4e0ad518ce2905ac58ab6fcd,
        0x4268c203f18d361afc33a2d15356a4e64f2ca1f507bcefaf6e0daa5a2c4c4b8,
        0x31f82f7b110cf0fedec4381eb2b4ef7bbfb6241276ad81e99f23e64ea3457d2,
        0x55ce2b27b18dc167740cea55bfba4c920bf41455caf86c7ea4b9f7a614b3ac,
        0x1d2fd418edbc17be7e37a4d07fb3f910801b4a469fdcb6ba2ee6156294668,
        0x4f9b1a51a3ec0964b97c108efe065f54e6edd63cf2ef40dfc93f590437cae58,
        0x11d6400cced0057f253dd0f4906d202daec97295c251c1eb3a3ae13bf4442c5,
        0x2828ea3570ae2642abdf689ca78220d7dc45b7be0cc1ae97089a8fe89c739e1,
        0x54355cfccf17e98bf076e119955b58d531ab864c4f8b9606779ec0117ef3fac,
        0x3e170baf04d290e76759a1e2b67fa63739578d9883b7bdc6ba98afffc8992c5,
        0xce682ba73ca032d5dd0f2ccb29a1834b51d4dc850486cf08fdce6969203917,
        0x36480f71ded7948935f02b3755f9c79c3419476c69dfbe5ff9dc742b7136623,
        0x27a7269fa0c704fb77ff85b9579c7b81591a63ac1a68f5763e972d2941b10d1,
        0x1efdc54c79b7b0830cf54eaf000851aea6c543f7d12a193d4e2d596e905a7d8,
        0x3378095e3b6b35069a13555a585e41a8497cacf482520ed422d8a6addf0115a,
        0x1b31d8bdb4b4ca31bbf3902884c8be863315e8433a22e4aa2090c55f236b9a1,
        0x20a0570911d8a00c74573184ac517730de6f8cc0ca547f3449865eeb62b5b45,
        0x57ae865f1792ab222addcd9174fa8ef11d8d4e70149324ec901f7674a18d575,
    ]
}
