//! Two-half forks of the four generated component evals that exceed the
//! 81,920-felt Sierra class cap on their own (docs/lane2-design.md, "Class
//! sizes v2"): each vendored `evaluate_constraints_at_point` is split at
//! the generated `lookup_constraints` seam into `half_a` (trace-mask
//! constraint quotients; returns the seam carry of QM31 numerators +
//! combined lookup denominators) and `half_b` (interaction-mask logup
//! constraints, resumed from the carry). Generated by
//! scripts/split_component_evals.py — do not edit by hand.

pub mod blake_compress_opcode;
pub mod blake_round;
pub mod cube_252;
pub mod poseidon_aggregator;
